[variables]
NIXPACKS_PYTHON_VERSION = "3.10"
PIP_BREAK_SYSTEM_PACKAGES = "1"
TF_CPP_MIN_LOG_LEVEL = "2"
DISABLE_TENSORFLOW_GPU = "1"
PIP_NO_CACHE_DIR = "1"

[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.virtualenv"]
nixLibs = ["zlib", "openssl", "libffi", "glib"]
nixOverlays = ["https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz"]

[phases.install]
cmds = [
    "/root/.nix-profile/bin/pip install --break-system-packages --upgrade pip setuptools wheel",
    "/root/.nix-profile/bin/pip uninstall -y tensorflow tensorflow-gpu tensorflow-cpu || true",
    "/root/.nix-profile/bin/pip install --break-system-packages --no-cache-dir --force-reinstall -r requirements-render.txt"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd backend && gunicorn --bind 0.0.0.0:$PORT app:app --timeout 300 --workers 1 --threads 2 --max-requests 1000 --max-requests-jitter 100"