[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
PIP_BREAK_SYSTEM_PACKAGES = "1"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]
nixLibs = ["zlib", "openssl", "libffi", "glib"]

[phases.install]
cmds = [
    "cd backend",
    "pip install --upgrade pip",
    "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "cd backend && python app.py"